[package]
name = "botnanars"
version = "0.3.9"
authors = ["Mapacode Inc."]
license = "LicenseRef-Mapacode-Proprietary"
edition = "2018"

[dependencies]
ws = "0.8"
libc = "0.2.41"
url = "1.7.0"
serde_json = "1.0.33"

[dev-dependencies]
serde = "=1.0.136"

