[package]
name = "libbotnana"
version = "0.1.0"
authors = ["Sirius Wu <ccwu660601@gmail.com>"]

[lib]
name = "botnana"
crate-type = ["cdylib"]

[dependencies]
libc = "*"
botnanars = { path = "../botnanars" }
futures = "0.1"
websocket = "0.20.2"
