[package]
name = "botnanac"
version ="0.3.5"
authors = ["Mapacode Inc."]

[dependencies]
libc = "0.2"
botnanars = {git="https://github.com/botnana/botnana-api-rs.git"}

[lib]
name="botnana"
crate-type = ["staticlib", "cdylib"]