[package]
name = "botnanac"
version = "0.2.1"

[dependencies]
ws = "0.7.6"
libc = "0.2.41"
url = "1.7.0"
serde_json = "1.0.33"

[dev-dependencies]
serde = "=1.0.60"

[lib]
name="botnana"
crate-type = ["staticlib", "cdylib"]