[package]
name = "botnanac"
version ="0.3.8"
authors = ["Mapacode Inc."]
edition = "2018"

[dependencies]
libc = "0.2"
botnanars = { path="../../botnana-api-rs" }

[lib]
name="botnana"
crate-type = ["staticlib", "cdylib"]
