[package]
name = "botnanac"
version ="1.13.45"
authors = ["Mapacode Inc."]
edition = "2018"

[dependencies]
libc = "0.2"
botnanars = { path="../botnana-api-rs" }

[lib]
name="botnana"
crate-type = ["staticlib", "cdylib"]
